default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "postgres") %>

development:
  <<: *default
  database: book_store_development

test:
  <<: *default
  database: book_store_test

production:
  <<: *default
  database: book_store_production
